base_config: &base_config
  USERNAME: username
  PASSWORD: password

development: &development
  <<: *base_config

test: &test
  <<: *base_config

production: &production
  USERNAME: username
  PASSWORD: password